name: Daily Weather Notice

on:
  schedule:
    - cron: '0 21 * * *'  # 日本時間で朝6時 (UTC 21:00)
  workflow_dispatch:  # 手動実行用

jobs:
  send-weather:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install line-bot-sdk requests google-generativeai
    
    - name: Run weather notification script
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python weather_line_bot.py